### PR TITLE
Re-add bidirectional edges in graph in order to correctly compute the domination graph edges

### PR DESCRIPTION
**Pull request by sgsmob**
This changes the catlases, but it makes them correct.  Addresses the issues in #97 in a way that works on `podar` and `hu_subset`.

### CODE REVIEW

**Comment by ctb** [comment]
Is this ready to merge?

**Comment by sgsmob** [comment]
If you want something that works, then yes.

**Comment by sgsmob** [comment]
By that I mean, if you are only looking for something that produces correct catlases, then this is good.  I don't have a more elegant long term solution so this may have to suffice for now.

**Comment by ctb** [comment]
what I was really looking for was: yes, go ahead and merge :)

**Pull request merged**
