### PR TITLE
[MRG] add translated catlas annotation functionality w/multifasta approach

### LINKED ISSUE #437: thoughts about annotating a cDBG with protein queries
If #379 can be finagled to operate like `multifasta query`, then protein queries could be used to annotate a cDBG. 
One thing I've run into trouble with in annotating cDBGs with nucleotide `multifasta queries` is that the multifasta file I query with isn't complete, e.g. many of the nodes in the cDBG/level 1 dominating set don't end up being annotated because their is no way to generate sufficient reference sequences (I'm guessing this is because of HGT, etc). #428 has numbers for # nodes annotated with different multifasta queries. It was a pain generating each of the multifasta queries -- because I knew the taxonomic identity of my catlas, I downloaded all the isolates genomes from refseq for those genomes. I also made my own gene catalogs by assembling and predicting genes from each query nbhd from the metagenomes. Which is to say, it was A LOT of work and a lot of compute and some really annoying snakemake rules. There is a lot of room for user-experience improvement for annotating a cDBG/catlas.

Using protein queries may annotate more of the graph, and be easier. 

To understand whether this has a chance of being accurate, I think we could check and see how many k-mers are shared between orthologs. If most kmers are unique to ortholog families, we could generate a set of kmers that are unique to each ortholog family and annotate the graph using these. While it would be wonderful to predict orthologs from all the genes in all the genomes in GTDB, that's probably too heavy handed for a test idea. May be quick and easy to download AA seqs that lead to pfam profiles, make a protein signature for each profile, and compare them. If there's low overlap, this could be a tractable idea. 

@bluegenes has done some of this work, more later!

### PR DESCRIPTION
**Pull request by ctb**
Note: this is a PR into #379, although it doesn't really need to be.

Fixes #437.

This PR extends the multifasta indexing/annotation capabilities added in https://github.com/spacegraphcats/spacegraphcats/pull/282 with protein queries. Briefly, it:
* adds a new script `spacegraphcats/search/index_cdbg_by_multifasta_x.py` that does protein-space search of the cDBG + expansion to neighborhoods;
* adds three new config parameters, `multifasta_x_reference`, `multifasta_x_protein_ksize`, and `multifasta_x_query_is_dna`.
* adds two new concrete targets in the Snakefile, `build_multifasta_x_index` and `build_cdbg_list_by_record_x`;
* the target `build_cdbg_list_by_record_x`  produces a file `{catlas_dir}_multifasta_x/multifasta_x.cdbg_annot.csv` that contains the nice mappings between neighborhoods and protein annotations;
* adds tests and docstrings;

As with protein query of the catlas #379, this PR cannot use the pre-built k-mer index to search the cDBGs. So, it does an iterative search of all the unitigs, which might take a while for large catlases. See some of the benchmark times, below.

TODO:
- [x] fix/retain filenames for each record
- [x] add config options into Snakefile, etc.
- [x] figure out how to produce `multifasta.cdbg_annot.csv`
- [x] testing, robustness, etc.
- [x] evaluate speed, functionality on a bigger catlas than dory...
- [x] add docstrings to top of multifasta scripts

## Example

To annotate the twofoo cDBG with a ~dozen genes, run:

```
python -m spacegraphcats run twofoo build_cdbg_list_by_record_x
```
and you'll get output like so:
```
...
saved 11 query names with cDBG node mappings (of 11 queries total)
saved 355 cDBG IDs (of 206855 total; 0.2%) with at least one query match
```
(This only takes 35 seconds or so, which is pretty good!)

## A larger query: time

I downloaded a full _Shewanella baltica_ proteome, GCF_001620325.1_ASM162032v1_protein.faa.gz, which has almost 4300 proteins in it, and ran this code.

Results:
```
...
saved 3769 query names with cDBG node mappings (of 4255 queries total)
saved 155286 cDBG IDs (of 206855 total; 75.1%) with at least one query match
```
and time:
```
real    0m43.729s
user    0m37.468s
sys     0m2.704s
```
so, that's pretty fast!

### CODE REVIEW

**Comment by ctb** [comment]
Ready for review, @taylorreiter!

I suggest merging #379 and #442 first ;).

**Comment by ctb** [comment]
Hmm, one idle thought to explore: we could use an LCA database from sourmash to speed things up here...

**Comment by taylorreiter** [comment]
I haven't assessed accuracy yet, but this works and the output files are in great formats!

**Review by taylorreiter — APPROVED** [review]
LGTM :)

**Comment by ctb** [comment]
I'll go ahead and merge this into #379, once the tests pass. #379 may need to wait for merge into `latest` until #447 is tracked down, tho.

**Pull request merged**
