### PR TITLE
[MRG] Update the requirements.txt for khmer release, add numpy.

### PR DESCRIPTION
**Pull request by ctb**
- [ ] Does this PR change the contracted DBG, catlas, or minhash DB formats?
      If so, merge with care as this will require rebuilding some big files.

### CODE REVIEW

**Comment by sgsmob** [comment]
@ctb is this request ready to merge once it passes the tests or is it a work in progress?

**Comment by ctb** [comment]
ready to merge!

**Comment by sgsmob** [comment]
Looks like you are checking for a command line option that no longer exists

**Comment by ctb** [comment]
how odd I thought I had removed those in the code... ok, well, I'll take
a closer look later :)

**Pull request merged**
