### PR TITLE
Decrease RAM usage.

### PR DESCRIPTION
**Pull request by ctb**

### CODE REVIEW

**Comment by ctb** [comment]
@domoritz it seems like I need to edit the Travis-CI configuration to run the setup.py build command - see 'make all' in this branch. Any tips on doing that? thx!

**Comment by domoritz** [comment]
@ctb you can put any commands in the `install` or `before_install` block of `.travis.yml` in this repo.

**Comment by ctb** [comment]
thanks @domoritz!

**Comment by ctb** [comment]
Wasn't ready for merging - a bug to clean up, at the minimum. I'll be more careful about putting a work in progress flag on them, and I'll submit a new PR in the morning to fix the problem :)

**Comment by domoritz** [comment]
Sorry about that. I reverted everything and added a WIP flag.

**Comment by ctb** [comment]
no worries & thanks :)

**Comment by domoritz** [comment]
Apparently we need a new pr. It's not at #24.

**Pull request merged**
