### PR TITLE
Remove the need for a bunch of dictionary lookups and make all in_neighbors calls use an explicit r

### PR DESCRIPTION
**Pull request by domoritz**
Fixes https://github.com/spacegraphcats/spacegraphcats/issues/50

### CODE REVIEW

**Comment by sgsmob** [comment]
I don't understand what line 219 is supposed to be doing.  It might be missing an assignment `=` somewhere

**Comment by domoritz** [comment]
@sgsmob Ups. That was supposed to be an assignment. The idea is that instead of doing the lookups all the time, we keep track of the dom distance of v in a separate variable.

**Comment by sgsmob** [comment]
Once that is fixed I think this is good to go

**Comment by sgsmob** [comment]
actually, no, the iteration on line 224 should run an additional time to get edges of weight radius

**Comment by domoritz** [comment]
Great. I amended the commit so it's correct now.

**Comment by domoritz** [comment]
> actually, no, the iteration on line 224 should run an additional time to get edges of weight radius

Good catch. I assumed that `domdistance[u]` is at least 1 but it could be 0, right?

**Comment by domoritz** [comment]
@sgsmob Thanks for the review. Should be correct now.

**Comment by sgsmob** [comment]
it is only 0 if u is in the dominating set.  However, there are no neighbors of a vertex v at radius 0 (trying this will raise an out of bounds exception

**Pull request merged**
