### PR TITLE
[MRG] add dominator abundance counting, per sample.

### PR DESCRIPTION
**Pull request by ctb**
This PR adds graph and dominator abundance counting: given a catlas and a sample, calculate the abundances of the cDBG nodes and catlas domset in the sample, using k-mers.

One use for this is when you have a catlas built from multiple samples, and you want to output expression directly on the domset using abundances from individual samples. This then could then be used to do differential expression analysis with e.g. corncob.

Usage:
```
python -m spacegraphcats.search.count_dominator_abundance twofoo_k31/ twofoo_k31_r1/ data/2.fa.gz data/63.fa.gz
```

This will create four files, `twofoo_k31_r1_abund/{2,63}.fa.gz.cdbg_abund.csv` and `twofoo_k31_r1_abund/{2,63}.fa.gz.dom_abund.csv`. The `cdbg_abund.csv` files contain the columns `cdbg_id,abund,node_size`, and the `dom_abund.csv` files contain the columns `dom_id,level,abund,size`. Here `abund` is the abundance calculated from the sample given , while `size` is the total number of distinct k-mers beneath that node.

The output directory can be overridden with `--outdir`, and the prefix of the output files can be overridden with `--prefix`.

TODO:
- [x] add some minimal tests!
- [x] update documentation at top
- [x] consider moving scripts under spacegraphcats/ package

### CODE REVIEW

**Comment by taylorreiter** [comment]
oooh I really like that these are utility scripts outside of the snakemake workflow -- it doesn't trigger snakemake to resolve its DAG, but only looks at the necessary files. This is really portable and nice for post-processing without having to worry about file dependencies/snakemake time stamps etc.

so far, successfully ran both scripts on dory and one real metagenome with one real query!

unimportant side request -- is it possible to export the script directory to the path when installing with `pip -e` or when installing from a branch, or i guess when installing ever?

**Comment by taylorreiter** [comment]
`x` = `cDBG abundances` (aka unitig abundances)
`y` = `dom node abundances`

**Comment by taylorreiter** [comment]
hmmmm how can cdbg abundances have zero? is it based on the query? This graph was built from 6 genome query neighborhood read sets, and my "query" here was the same as the original query used to built the 6 genome query nbhds.

```
$ scripts/count-dominator-abundance.py rgnv_nbhd_baby_k31_r1/
../GCF_900036035.1_RGNV35913_genomic.fna.gz rgnv_nbhd_baby_unitig_abund.txt rgnv_nbhd_baby_domset_abund.txt

loaded 815529 nodes from catlas rgnv_nbhd_baby_k31_r1/
loaded 434835 layer 1 catlas nodes
loaded 13330714 k-mers in index (2.4s)
reading sequences from ../GCF_900036035.1_RGNV35913_genomic.fna.gz
done! read 3730844 total k-mers.
outputting cDBG abundances to rgnv_nbhd_baby_unitig_abund.txt
outputting dom node abundances to rgnv_nbhd_baby_domset_abund.txt

$ ls
rgnv_nbhd_baby                     rgnv_nbhd_baby_k31_r1
rgnv_nbhd_baby_catlas_r1_conf.yml  rgnv_nbhd_baby_unitig_abund.txt
rgnv_nbhd_baby_domset_abund.txt
$ less rgnv_nbhd_baby_unitig_abund.txt
```

```
cdbg_id,abund
0,0
1,0
2,0
3,0
4,0
5,0
6,0
7,0
8,0
9,0
10,0
11,0
12,0
13,1
14,0
15,0
16,4
17,0
18,0
19,0
20,0
```

**Comment by taylorreiter** [comment]
please disregard the above. I had a momentary lapse where I forgot, you know, the purpose of spacegraphcats.

**Comment by ctb** [comment]
😂

**Comment by ctb** [comment]
hmm - I could _add_ the query as an (optional) filter, e.g. switch from

"give me the abundances of ALL dom nodes in the graph, using abundances from sample X"

to

"give me the abundances of all dom nodes in the query neighborhood for Y, using abundances from sample X"

- let me know if that would substantially simplify things for you.

**Comment by ctb** [comment]
Other thought - on the annotation output file, I could provide a single file with `dom node,cdbg node,annotation` in it rather than two separate files.

**Comment by taylorreiter** [comment]
>"give me the abundances of ALL dom nodes in the graph, using abundances from sample X"
>
>to
>
>"give me the abundances of all dom nodes in the query neighborhood for Y, using abundances from sample X"
>
>   let me know if that would substantially simplify things for you.

No! the first is much simpler I think, I just got confused :)

> Other thought - on the annotation output file, I could provide a single file with dom node,cdbg node,annotation in it rather than two separate files.

Nah, two separate files is fine. It's easy enough to join them together if I need all of the information

**Comment by taylorreiter** [comment]
Not a huge deal esp bc premature optimization is the root of all evil, but I have the catlas built for my 605 query nbhds and this went from lightning fast to not lightning fast, I think because the catlas is getting loaded into memory each time I'm running it. could be nice to feed it a list of files I want quantified (e.g as a conf), and only have to read in the catlas once. 

again though, probably not a worth it thing until we have actual results showing this works! Also I could be totally wrong and catlas-loading could not be the slow part.

**Comment by ctb** [comment]
easy to do! what filename pattern do you suggest for the outputs?

**Comment by ctb** [comment]
I've updated `count-dominator-abundance.py` to take in multiple query files and output "standardized" output file names; see top comment for revised usage.

**Comment by taylorreiter** [comment]
this is a very silly vanity suggestion, but would be be possible to name the dominators something like `d0` instead of `0`? Numbers aren't allowed as column names in R, so it's an extra processing step to do differential abundance (where the dominators become be the column names).

Tidyverse pseudo-fixes this, so if this numbering scheme is more deeply embedded in the catlas itself, then I default to not changing it. But if the numbers are sort of random and it doesn't matter what the dominators are called, then I think adding `d0` or `dom0` to the name could be nice. 

```
$ head 4000_rgnv_nbhd_domset_abund.txt
dom_id,abund
0,0
1,0
2,0
3,0
4,0
5,0
```

**Comment by ctb** [comment]
> this is a very silly vanity suggestion, but would be be possible to name the dominators something like `d0` instead of `0`? Numbers aren't allowed as column names in R, so it's an extra processing step to do differential abundance (where the dominators become be the column names).
> 
> Tidyverse pseudo-fixes this, so if this numbering scheme is more deeply embedded in the catlas itself, then I default to not changing it. But if the numbers are sort of random and it doesn't matter what the dominators are called, then I think adding `d0` or `dom0` to the name could be nice.
> 
> ```
> $ head 4000_rgnv_nbhd_domset_abund.txt
> dom_id,abund
> 0,0
> 1,0
> 2,0
> 3,0
> 4,0
> 5,0
> ```

I mean, those are the dominator numbers ;). It is easy enough to rename them but you'd have to strip off the prefix if you wanted to connect them back to internal numbers.

Is there maybe a simple way to have #rstats functions add the prefix?

If we did this, I might want to make it part of a larger output renaming where we more clearly distinguish between cDBG nodes and dom nodes internally by adding prefixes to both. It won't matter at all to the way we treat them in the wrapping Python code (which mostly uses dictionaries, and does int conversions for convenience rather than performance reasons) and it might help make the code more readable.

**Comment by taylorreiter** [comment]
Yup! there is a simple rstats function/code I can use to do this. Better to leave as is, was just wondering.

**Comment by taylorreiter** [comment]
Brand new error:

```
Traceback (most recent call last):
  File "/home/tereiter/github/spacegraphcats/scripts/count-dominator-abundance.py", line 89, in <module>
    sys.exit(main())
  File "/home/tereiter/github/spacegraphcats/scripts/count-dominator-abundance.py", line 40, in main
    len(kmer_idx.mphf_to_kmer), time.time() - ki_start)
```

This is with `latest`, but using the script `scripts/count-dominator-abundance.py` in this branch.

**Comment by ctb** [comment]
On Mon, May 17, 2021 at 06:10:18PM -0700, Taylor Reiter wrote:
> Brand new error:
> 
> ```
> Traceback (most recent call last):
>   File "/home/tereiter/github/spacegraphcats/scripts/count-dominator-abundance.py", line 89, in <module>
>     sys.exit(main())
>   File "/home/tereiter/github/spacegraphcats/scripts/count-dominator-abundance.py", line 40, in main
>     len(kmer_idx.mphf_to_kmer), time.time() - ki_start)
> ```
> 
> This is with `latest`, but using the script `scripts/count-dominator-abundance.py` in this branch. 

I think you're missing part of the error message?

**Comment by taylorreiter** [comment]
huh yup...sorry!

```
for infile in ../../rgnv_sgc_original_r
esults/*gz
> do
> bn=$(basename $infile .fa.gz)
> ~/github/spacegraphcats/scripts/count-dominator-abundance.py rgnv_nbhd_diginorm_k31_r10/ ${infile} rgnv_count_dom_out/${bn}_rgnv_nbhd_unitig_abund.txt rgn
v_count_dom_out/${bn}_rgnv_nbhd_domset_abund.txt
> done
loaded 6065364 nodes from catlas rgnv_nbhd_diginorm_k31_r10/
loaded 5993945 layer 1 catlas nodes
Traceback (most recent call last):
  File "/home/tereiter/github/spacegraphcats/scripts/count-dominator-abundance.py", line 89, in <module>
    sys.exit(main())
  File "/home/tereiter/github/spacegraphcats/scripts/count-dominator-abundance.py", line 40, in main
    len(kmer_idx.mphf_to_kmer), time.time() - ki_start)
AttributeError: 'MPHF_KmerIndex' object has no attribute 'mphf_to_kmer'
```

**Comment by ctb** [comment]
fixed in 209d450669! also updated the branch from `latest`.

**Comment by ctb** [comment]
So I added information about size and abundances for each catlas node at each level, as well as the size for each cDBG node, to the outputs. The goal was to allow @taylorreiter to do differential abundance analysis at each level of the catlas.

The problem is that only level 1 and the root node of the catlas are guaranteed to contain all cDBG nodes under them. I think this is because once a component is entirely contained within a catlas node, it is attached directly to the root node of the catlas and no other higher catlas levels contain it.

The practical effect of this is that you see a steady decline in the number of k-mers beneath each level in the catlas, until you get to the root note; so, in the dict below, level 1 and level 25 have all the k-mers in the cDBG, but level 2, 3, 4, etc. steadily lose them. Level 24 presumably contains only the largest component ;).

```
sum level sizes: defaultdict(<class 'int'>, {1: 10028763, 2: 9418834, 3: 9401348, 4: 9333106,
5: 9206229, 6: 8994966, 7: 8663387, 8: 7903810, 9: 6565173, 10: 5504394,
11: 5162151, 12: 4984791, 13: 4980593, 14: 4934749, 15: 4925884, 16: 4908648,
17: 4745012, 18: 4745012, 19: 4644447, 20: 4638222, 21: 4601280, 22: 4594741,
23: 4593470, 24: 4556055, 25: 10028763})
```

this of course also affects the per-level abundance counts,
```
level_counts: defaultdict(<class 'int'>, {1: 5068158, 2: 5018133, 3: 5002192, 4: 4940226,
5: 4830038, 6: 4661702, 7: 4426368, 8: 3888070, 9: 2969043, 10: 2228829,
11: 1988778, 12: 1849066, 13: 1846273, 14: 1814644, 15: 1808198, 16: 1796660,
17: 1679284, 18: 1679284, 19: 1607172, 20: 1603124, 21: 1576631, 22: 1571840,
23: 1570903, 24: 1544225, 25: 5068158})
```

Will think on this to see if there's a good way to proceed with making levels comparable. I keep on circling around the idea of taking dom nodes that are attached to the root node and making them honorary members of each level between their level and the root level...?

**Comment by taylorreiter** [comment]
> So I added information about size and abundances for each catlas node at each level, as well as the size for each cDBG node, to the outputs. The goal was to allow @taylorreiter to do differential abundance analysis at each level of the catlas.
> 
> The problem is that only level 1 and the root node of the catlas are guaranteed to contain all cDBG nodes under them. I think this is because once a component is entirely contained within a catlas node, it is attached directly to the root node of the catlas and no other higher catlas levels contain it.
> 
> The practical effect of this is that you see a steady decline in the number of k-mers beneath each level in the catlas, until you get to the root note; so, in the dict below, level 1 and level 25 have all the k-mers in the cDBG, but level 2, 3, 4, etc. steadily lose them. Level 24 presumably contains only the largest component ;).
> 
> ```
> sum level sizes: defaultdict(<class 'int'>, {1: 10028763, 2: 9418834, 3: 9401348, 4: 9333106,
> 5: 9206229, 6: 8994966, 7: 8663387, 8: 7903810, 9: 6565173, 10: 5504394,
> 11: 5162151, 12: 4984791, 13: 4980593, 14: 4934749, 15: 4925884, 16: 4908648,
> 17: 4745012, 18: 4745012, 19: 4644447, 20: 4638222, 21: 4601280, 22: 4594741,
> 23: 4593470, 24: 4556055, 25: 10028763})
> ```
> 
> this of course also affects the per-level abundance counts,
> 
> ```
> level_counts: defaultdict(<class 'int'>, {1: 5068158, 2: 5018133, 3: 5002192, 4: 4940226,
> 5: 4830038, 6: 4661702, 7: 4426368, 8: 3888070, 9: 2969043, 10: 2228829,
> 11: 1988778, 12: 1849066, 13: 1846273, 14: 1814644, 15: 1808198, 16: 1796660,
> 17: 1679284, 18: 1679284, 19: 1607172, 20: 1603124, 21: 1576631, 22: 1571840,
> 23: 1570903, 24: 1544225, 25: 5068158})
> ```
> 
> Will think on this to see if there's a good way to proceed with making levels comparable. I keep on circling around the idea of taking dom nodes that are attached to the root node and making them honorary members of each level between their level and the root level...?

So I hope i don't butcher the language here but:
+ all cDBG nodes belong to a level 1 dominator. These are level 1 pieces. 
+ don't all level 1 pieces belong to a level 2 dominator (which is contained in the level 1 dominators as well, but level 2 are a subset of level 1?) 
+ so on an so forth up to level X

so...couldn't we recursively assign nodes/level1 pieces to their levels and go from there?

**Comment by taylorreiter** [comment]
@ctb...I just realized I don't actually know what the abundances are in the output column. Is it the sum of abundances of all kmers that occur in a piece? It has nothing to do with reads right?

**Comment by ctb** [comment]
> @ctb...I just realized I don't actually know what the abundances are in the output column. Is it the sum of abundances of all kmers that occur in a piece? It has nothing to do with reads right?

k-mers.

**Comment by ctb** [comment]
> > 
> 
> So I hope i don't butcher the language here but:
> 
>     * all cDBG nodes belong to a level 1 dominator. These are level 1 pieces.
> 
>     * don't all level 1 pieces belong to a level 2 dominator (which is contained in the level 1 dominators as well, but level 2 are a subset of level 1?)
> 
>     * so on an so forth up to level X
> 
> 
> so...couldn't we recursively assign nodes/level1 pieces to their levels and go from there?

yes, this is what I tried, but I ran afoul of one implementation detail:

not all level N pieces belong to a level N+1 piece - if the level N piece is an entire component (== disconnected portion of graph) it gets attached directly to the root catlas node. I can write logic to get around this but have not yet done so.

**Comment by ctb** [comment]
hah, here is the key comment from [above](https://github.com/spacegraphcats/spacegraphcats/pull/303#issuecomment-847892619)

>The problem is that only level 1 and the root node of the catlas are guaranteed to contain all cDBG nodes under them. I think this is because once a component is entirely contained within a catlas node, it is attached directly to the root node of the catlas and no other higher catlas levels contain it.

this was confirmed with Felix.

**Comment by ctb** [comment]
hi @taylorreiter I just updated this PR to 'rescue' the missing catlas nodes in the `*.dom_abund.csv` files.

this means that if you pick a particular level out of the file (by selecting a particular number on column 2), the sum of the abundances and k-mer sizes for that level will be the same as for any other level as well as for the whole graph. 🎉 

on the flip side, if you look at the `*.dom_abund.csv` file, you'll see something like this:
```csv=
dom_id,level,abund,size
131003,3,71,102
131003,4,71,102
131003,5,71,102
131003,6,71,102
131003,7,71,102
...
131003,21,71,102
131003,22,71,102
131003,23,71,102
131003,24,71,102
```
where dom_id=131003 is attached directly to the root at level 2, and as soon as you go above that level, it appears redundantly at _every_ level. This might affect the way you read the file; in particular, the dom_id is no longer a unique key.

Also, please let me know if you're using these scripts and if so I'll add them to our testing regimen and put this PR up for merge ;).

**Comment by taylorreiter** [comment]
@ctb I am using these scripts. I haven't tested out your "rescue" method, but everything before then has been wonderful and I've used it a bunch and it's worked really well.

**Comment by ctb** [comment]
> @ctb I am using these scripts. I haven't tested out your "rescue" method, but everything before then has been wonderful and I've used it a bunch and it's worked really well.

lovely to hear :)

**Comment by taylorreiter** [comment]
would it be possible to specify the output directory/file prefix instead of inheriting the directory from the reads? I don't mind the automatic file endings (dom_abund.csv, cdbg_abund.csv) but the other two things are sort of a pain to work around in snakemake

**Comment by ctb** [comment]
> unimportant side request -- is it possible to export the script directory to the path when installing with `pip -e` or when installing from a branch, or i guess when installing ever?

not really. I mean, there are ways to do it, but it's better to have it under the spacegraphcats package.

**Comment by ctb** [comment]
> would it be possible to specify the output directory/file prefix instead of inheriting the directory from the reads? I don't mind the automatic file endings (dom_abund.csv, cdbg_abund.csv) but the other two things are sort of a pain to work around in snakemake

OK, so what we're doing is:
```
for sample in args.samples:
   ...
   outfile = f"{sample}.cdbg_abund.csv"
   ...
   outfile = f"{sample}.dom_abund.csv"
```
where `args.samples` comes from the command line as all things after the cDBG and catlas prefix.

So, both directory and prefix do come from the sample files (aka reads, as you say above).

It's easy to strip off the directory prefix with `os.path.basename` and then add a parameter like `--outdir` that specifies where to put the files, or `--prefix` that just prepends whatever (including directory). Preference between the two?

I'm stuck on what to name the files, though. Since there are multiple input files possible (per your optimization request above ;), we can't easily specify the output file names on the command line. Thoughts/hopes/dreams/requests?

**Comment by taylorreiter** [comment]
> > would it be possible to specify the output directory/file prefix instead of inheriting the directory from the reads? I don't mind the automatic file endings (dom_abund.csv, cdbg_abund.csv) but the other two things are sort of a pain to work around in snakemake
> 
> OK, so what we're doing is:
> 
> ```
> for sample in args.samples:
>    ...
>    outfile = f"{sample}.cdbg_abund.csv"
>    ...
>    outfile = f"{sample}.dom_abund.csv"
> ```
> 
> where `args.samples` comes from the command line as all things after the cDBG and catlas prefix.
> 
> So, both directory and prefix do come from the sample files (aka reads, as you say above).
> 
> It's easy to strip off the directory prefix with `os.path.basename` and then add a parameter like `--outdir` that specifies where to put the files, or `--prefix` that just prepends whatever (including directory). Preference between the two?
> 
> I'm stuck on what to name the files, though. Since there are multiple input files possible (per your optimization request above ;), we can't easily specify the output file names on the command line. 

Thoughts/hopes/dreams/requests:

Strip pathname with `os.path.basename`, keep the file prefix and add dom_abund.csv/cdbg_abund.csv to the end. 
Then output dir specified by `--outdir`, or by default could be `{catlas_dir}_abund `

**Comment by ctb** [comment]
> Strip pathname with `os.path.basename`, keep the file prefix and add dom_abund.csv/cdbg_abund.csv to the end.
> Then output dir specified by `--outdir`, or by default could be `{catlas_dir}_abund `

So,

```
scripts/count-dominator-abundance.py twofoo_k31/ twofoo_k31_r1/ data/2.fa.gz data/63.fa.gz --output-dir foo
```

will create four files, `foo/{2,63}.fa.gz.cdbg_abund.csv` and `foo/{2,63}.fa.gz.dom_abund.csv`.

And `--output-dir` will default to `{catlas_dir}_abund` so in this case `twofoo_k31_r1_abund`.

Should I add this to the config file, too, so that there is a list of files for which to calculate abundances? 🤔 That can maybe wait because it seems like you're ok using these as scripts.

**Comment by ctb** [comment]
so mote it be! 25fd59f

FYI, usage information in top comment updated.

**Comment by taylorreiter** [comment]
Ok so using this now and am realizing i was being kind of silly in my suggestion...but i still don't totally dislike it and i'm not sure it should change right away at least bc i sort of want to use it as-is. 

So...in the above example, the output file scheme is perfect. But imagine the not-so-hypothetical situation where you have multiple metagenomes query nbhds from previous sgc queries that you want to calculate abundances for. The prefix would always be the same, e.g. {2,63}, and would overwrite for each different library. So maybe my request is to also add an optional prefix argument, similar to the outdir argument, where the default behavior is great as is? Sorry if this is convoluted...I can explain again in a different way if it isn't clear

**Comment by ctb** [comment]
> Ok so using this now and am realizing i was being kind of silly in my suggestion...but i still don't totally dislike it and i'm not sure it should change right away at least bc i sort of want to use it as-is.
> 
> So...in the above example, the output file scheme is perfect. But imagine the not-so-hypothetical situation where you have multiple metagenomes query nbhds from previous sgc queries that you want to calculate abundances for. The prefix would always be the same, e.g. {2,63}, and would overwrite for each different library. So maybe my request is to also add an optional prefix argument, similar to the outdir argument, where the default behavior is great as is? Sorry if this is convoluted...I can explain again in a different way if it isn't clear

Not silly at all ;). So, initially, I was thinking that `--outdir` essentially acts as the prefix option you want,

e.g.
```
scripts/count-dominator-abundance.py twofoo_k31/ twofoo_k31_r1/ data/2.fa.gz data/63.fa.gz --outdir twofoo_k31_r1_abund/XYZ.
```

will create four files, `twofoo_k31_r1_abund/XYZ.{2,63}.fa.gz.cdbg_abund.csv` and `twofoo_k31_r1_abundXYZ./{2,63}.fa.gz.dom_abund.csv.`

_but_ after double checking the code, I do some stuff to check that the directory etc exists, so I will add a `--prefix` option as well!

(Added in df5f5e5)

**Comment by ctb** [comment]
@taylorreiter is this something we should consider merging?

**Comment by taylorreiter** [comment]
Yes I think so!

**Comment by ctb** [comment]
ok - turns out I didn't actually write tests for it, so, um, I'll do that first ;)

**Comment by ctb** [comment]
@taylorreiter are you using / have you used `scripts/output-dominator-multifasta-annotations.py`?

**Comment by ctb** [comment]
OK, I've moved `scripts/count-dominator-abundance.py` to `spacegraphcats/search/count_dominator_abundance.py`.

This means that the script is now installed with `pip install`, and you should now run it with:

```
python -m spacegraphcats.search.count_dominator_abundance
```

I'm updating the runtime instructions in the PR description now.

I've also added a bunch of tests, yada yada.

I will refrain from updating `scripts/output-dominator-multifasta-annotations.py` until I hear that you're using it, taylor.

**Comment by ctb** [comment]
> I will refrain from updating `scripts/output-dominator-multifasta-annotations.py` until I hear that you're using it, taylor.

Actually, I think the cDBG functionality of this script is now redundant with the functionality added in #282 and https://github.com/spacegraphcats/spacegraphcats/pull/444, and I no longer trust the dominator/catlas output of this script so I'm removing it for now. I can put it back in if it's used somewhere.

**Comment by ctb** [comment]
Ready for review @taylorreiter

**Comment by taylorreiter** [comment]
Yay this is wonderful, and looks great!

I don't think I ever used `scripts/output-dominator-multifasta-annotations.py`, so all good there too!

**Comment by ctb** [comment]
🎉

**Pull request merged**
