### PR TITLE
Correct Jaccard computation

### PR DESCRIPTION
**Pull request by sgsmob**
The Jaccard computation was not being done mathematically correctly with the minhashes.  This is now fixed and using the frontier search with Jaccard similarity performs better than the "search by level" method.  The "worst node" refinement strategy, while correct, is very slow and basically returns the entire graph, so we should not use that in the future.

### CODE REVIEW

**Comment by ctb** [comment]
So, the Jaccard computation for the frontier search *specifically* was being done incorrectly -- right?

I'll merge this now, but -- is there a test for this? Or should we just nail down the general results and not unit test the Jaccard code?

**Comment by ctb** [comment]
OK, the non-memory-optimization bits of this were merged into master!

**Comment by sgsmob** [comment]
Yes.  The Jaccard similarity between sets A and B is estimated by 

| MH(A) intersect MH(B) | / (number of elements in MH)

We were previously not using the `MinHash.compare()` method, but rather were computing the Jaccard similarity between _the minhashes themselves_ i.e.

| MH(A) intersect MH(B) | / | MH(A) union MH(B) |

which does not properly estimate the Jaccard similarity of A and B.  The code as it was written correctly computed this other value, but it led to making poor decisions on the frontier search.

**Comment by ctb** [comment]
OK!

Any suggestions on how to best put in a test for this?

**Comment by sgsmob** [comment]
What exactly should be tested?  We can always just take a catlas and test if the Jaccard similarity estimate given by the minhashes of two nodes is close to the actual Jaccard similarity of the kmers at their leaves.  One issue there is that the actual Jaccard and estimated Jaccard might not be exactly equal simply based on the error incurred from a probabilistic data structure, or it might be off because the implementation is incorrect.  I don't really know how to distinguish between the two.

**Comment by ctb** [comment]
We could certainly test the properties of the MinHashes on the catlas, but
that is a scientific question for the whole project, really, and a bit too
fuzzy to put into the tests directly IMO.

I was thinking here that we should actually write a unit test on the
catlas code to make sure that when we take defined minhashes on nodes
we are computing the jaccard distance between them properly.  A code level
test, not a concept level test.

We don't have any on the catlas code right now, but see e.g. test_graph.py
for a simple example.  Basically, writing code that, if it breaks, demonstrates
that something is truly broken in the code.

**Pull request closed without merging**
