### PR TITLE
Polish and complete the initial query_by_hashval functionality.

### PR DESCRIPTION
**Pull request by ctb**
Add `spacegraphcats <conf> hashval_query` into the sgc workflows, to allow indexing and rapid querying of graph neighborhoods by sourmash hashvalue (scaled MinHash).

Briefly, the workflow:
* indexes the cDBG unitigs by building a map { hashval: unitig ID }
* allows search & retrieval of neighborhoods by one or more hash values (specified in a text file)

This PR also substantially refactors the `test_workflow` code to break the workflow tests out into different functions.

### dory-test

Run:
```
spacegraphcats dory-test hashval_query
```
to do an indexing at ksize=31 and query using the hashvals in `data/dory-hashval-queries.txt`; both of these are specified in the `spacegraphcats/conf/dory-test.yaml` file.

Output will be in `dory_k21_r1_hashval_k31/`, summary in `hashval_results.csv`.

### twofoo

Run:
```
spacegraphcats twofoo hashval_query
```
to do an indexing at ksize=31 and query using the hashvals in `data/twofoo-k31-hashval-queries.txt`; both of these are specified in the `spacegraphcats/conf/twofoo.yaml` file.

Output will be in `twofoo_k31_r1_hashval_k31/`, summary in `hashval_results.csv`.

## Notes

The `hashval_ksize` parameter can be different from the k-mer size used to build the cDBG! But for now you can only specify one in a config file; make duplicate config files with different hashval_ksize values to do queries on multiple ksizes.

## Further work

- [x] test indexing with different ksizes than catlas build!
- [x] the ksize column in `hashval_results.csv` isn't set currently
- [ ] explore multiple hashval_ksizes in a single config file (see e.g. [more complex yaml syntax](https://docs.ansible.com/ansible/latest/reference_appendices/YAMLSyntax.html))
- [ ] add this info to the documentation!

### CODE REVIEW

**Comment by taylorreiter** [comment]
@ctb both the dory and twofoo example exited with `FileNotFoundError: [Errno 2] No such file or directory: 'twofoo_k31_r1/catlas.csv'`

```
[Tue Sep 17 12:32:24 2019]
rule hashval_query:
    input: data/twofoo-k51-hashval-queries.txt, twofoo_k31_r1_hashval_k51/index.pickle
    output: twofoo_k31_r1_hashval_k51/hashval_results.csv
    jobid: 0

/home/tereiter/miniconda3/bin/python -m spacegraphcats.search.query_by_hashval -k 51 twofoo_k31_r1 twofoo_k31_r1_hashval_k51/index.pickle
 data/twofoo-k51-hashval-queries.txt twofoo_k31_r1_hashval_k51
putting output in twofoo_k31_r1_hashval_k51
loaded 691 hash value -> cdbg_id mappings from twofoo_k31_r1_hashval_k51/index.pickle
loaded 20 search hashvalues from data/twofoo-k51-hashval-queries.txt
Traceback (most recent call last):
  File "/home/tereiter/miniconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/tereiter/miniconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/tereiter/github/spacegraphcats/spacegraphcats/search/query_by_hashval.py", line 210, in <module>
    main(sys.argv[1:])
  File "/home/tereiter/github/spacegraphcats/spacegraphcats/search/query_by_hashval.py", line 159, in main
    catlas = CAtlas(args.catlas_prefix)
  File "/home/tereiter/github/spacegraphcats/spacegraphcats/search/catlas.py", line 27, in __init__
    self.__load_catlas(catlas_file)
  File "/home/tereiter/github/spacegraphcats/spacegraphcats/search/catlas.py", line 39, in __load_catlas
    for line in open(catlas_file, 'rt'):
FileNotFoundError: [Errno 2] No such file or directory: 'twofoo_k31_r1/catlas.csv'
```

**Comment by taylorreiter** [comment]
So I think `rule hashval_query` (https://github.com/spacegraphcats/spacegraphcats/blob/update/query_hashval/spacegraphcats/conf/Snakefile#L282) needs as input "{catlas_dir}/catlas.csv" for snakemake to properly solve dependencies and generate the necessary files. 

```
rule hashval_query:
    input:
        hashval_queries,
        expand("{hashval_query_dir}/index.pickle", hashval_query_dir=hashval_query_dir), 
        expand("{catlas_dir}/catlas.csv", catlas_dir=catlas_dir)
    output:
        expand("{hashval_query_dir}/hashval_results.csv", hashval_query_dir=hashval_query_dir)
#        make_query_base(config['search']),
    shell:
        "{python} -m spacegraphcats.search.query_by_hashval -k {hashval_ksize} {catlas_dir} {hashval_query_dir}/index.pickle {hashval_queries} {hashval_query_dir}"
```

i made the changes locally and this worked for me.

**Comment by taylorreiter** [comment]
@ctb is it possible to enable output of reads (either fastq or fasta) from `hashval_query`? The contigs are useful, but the reads would be even more useful!

**Comment by ctb** [comment]
@taylorreiter try new `extract_reads_for_hashvals` rule!

**Comment by ctb** [comment]
usage: ```spacegraphcats <conf> extract_reads_for_hashvals```.

Note, `--version` should work on this branch now, too.

**Comment by taylorreiter** [comment]
Tried! It fails if the hashval in the query file was not found in the catlas originally. My work around for this right now is to intersect my unassigned hashes with my list of cosmopolitan hashes and only search for those.

**Comment by ctb** [comment]
try now!

**Comment by taylorreiter** [comment]
works!

**Pull request merged**
