### PR TITLE
remove expensive check

### PR DESCRIPTION
**Pull request by sgsmob**
Removes a sanity check that is very expensive for upper levels of the catlas.  also did a little bit of PEP8 compliance so I don't have to look at the red squiggles in Atom ;)

### CODE REVIEW

**Comment by domoritz** [comment]
Should we keep these checks in the code but put them behind a flag (e.g. `--save` or `--with-checks`)?

**Comment by sgsmob** [comment]
No, I think we should be confident that our code runs correctly and if we did incorporate such a check, we would probably want to place a lot more throughout the code.

**Comment by sgsmob** [comment]
Also it appears that travis is not using the right version of sourmash.  Don't know how that ended up happening.

**Comment by domoritz** [comment]
This may have been fixed in https://github.com/spacegraphcats/spacegraphcats/commit/f768b6f68863d2393fb7d38724bb37bb11eac2b1.

**Pull request merged**
