### PR TITLE
Graph preprocessing

### PR DESCRIPTION
**Pull request by sgsmob**
Removes only pendants with low abundance and contracts degree two vertices where possible.

### CODE REVIEW

**Comment by ctb** [comment]
error --

```
% conf/run twofoo build --experiment=denoise2
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/t/dev/spacegraphcats/search/bcalm_to_gxt.py", line 276, in <module>
    main(sys.argv[1:])
  File "/Users/t/dev/spacegraphcats/search/bcalm_to_gxt.py", line 241, in main
    sizes, k)
  File "/Users/t/dev/spacegraphcats/search/bcalm_to_gxt.py", line 124, in contract_degree_two
    neighbors[u].remove(v)
KeyError: 75
```

**Comment by sgsmob** [comment]
I can't replicate this issue

**Comment by sgsmob** [comment]
This recreates the issue.  I must have had an old twofoo instance.  Will look into this.

**Comment by ctb** [comment]
thx!

**Comment by ctb** [comment]
in theory, 'conf/run twofoo clean' should have had you start from scratch.
but in fact that didn't work. I'm fixing it in #190

**Comment by sgsmob** [comment]
It appears the BCALM file is erroneous.  Unitig 20 is adjacent to unitig 111858 but 111858 claims it is adjacent to unitig 21.  21 does not claim to be adjacent to 111858.

**Comment by ctb** [comment]
yes, I see that as well. hmm.

**Comment by ctb** [comment]
whups, I do not have latest master. trying again.

**Comment by ctb** [comment]
(of bcalm)

**Comment by ctb** [comment]
This appears to no longer be a problem in the latest bcalm. yay!

**Comment by ctb** [comment]
(my apologies)

**Comment by sgsmob** [comment]
Is there an issue with Travis wrt the newest BCALM version?  Or is the build error actually capturing a bug in the code?

**Comment by ctb** [comment]
looks like it's downloading an old bcalm output. I will fix.

**Comment by ctb** [comment]
denoising v2 works as well on podarV as denoising v1 did - did not look at r1 search differences yet :) - https://github.com/TheoryInPractice/cats-in-practice/blob/master/results/results-podarV-denoising2-effect-may2.ipynb

**Comment by ctb** [comment]
I'm going to merge this into #190, fix the tests, and then merge to master.

**Comment by ctb** [comment]
I'm still having trouble running this on twofoo with the latest bcalm. Humm. @sgsmob I'm assuming the bcalm file is still effed up - can you show me how to debug/diagnose? https://osf.io/zgx3r/

**Comment by ctb** [comment]
(FWIW, I'm thinking we should go back to the last release of bcalm, and also file a bug report on bcalm.)

**Comment by sgsmob** [comment]
Is the error message you are getting the same one that Travis is?  bcalm_to_gxt.py should produce a file bcalm_to_gxt.log in the directory from which it was run for debugging purposes.  If it is nonempty, can you please send it to me?

**Comment by ctb** [comment]
it's empty...

**Comment by ctb** [comment]
using a new file, not the one Travis is using.

**Comment by sgsmob** [comment]
Ok if the log is empty the issue is probably that the bcalm file has non-reciprocal edges.

**Pull request merged**
