### PR TITLE
[MRG] add -k option to frontier search in case signature has multiple ksizes

### PR DESCRIPTION
**Pull request by ctb**
Ready for merge!

### CODE REVIEW

**Comment by domoritz** [comment]
Travis doesn't seem to be happy with Python 3.5.

**Comment by domoritz** [comment]
I restarted travis to see whether that fixes the build issue.

**Comment by domoritz** [comment]
@ctb Do you know why Sourmash does not compile under Python 3.5 anymore? https://travis-ci.org/spacegraphcats/spacegraphcats/jobs/241050673

**Comment by ctb** [comment]
my guess is: old version of setuptools.  Tried forcing an update, let's
see if it works!

**Comment by domoritz** [comment]
Looks like that was it.

**Pull request merged**
