### PR TITLE
Rules and modifications to extract reads and contigs for search results

### PR DESCRIPTION
**Pull request by ctb**
- [ ] Does this PR change the contracted DBG, catlas, or minhash DB formats?
      If so, merge with care as this will require rebuilding some big files.

### CODE REVIEW

**Comment by ctb** [comment]
this should be ready for review & merge, once the build passes (he says, optimistically).

**Comment by sgsmob** [comment]
@ctb I thought I pushed my changes to my copy of this branch on my fork but apparently it went to the upstream.  My commit passes some conf/run testing so as far as I know I haven't broken anything but I will do some more verification tomorrow.

**Comment by sgsmob** [comment]
my changes should be safe to merge.

**Comment by ctb** [comment]
Tests finally pass :). merging!

**Pull request merged**
