### PR TITLE
use contigs sqlite DB, rather than contigs.fa.gz, for contig retrieval

### PR DESCRIPTION
**Pull request by ctb**
In #338, which was merged into `latest` in #310, we changed things so that `sort_bcalm_unitigs` used SQLite as an on-disk store for sorting contigs into a deterministic order by min hash value in each sequence; `bcalm_to_gxt2` then used that to output the `contigs.fa.gz` indexed BGZF file used by downstream scripts to retrieve contigs.

This PR is experimenting with retrieving contigs from the already-created SQLite store, and dispensing with contigs.fa.gz entirely; there's no good reason to have two copies of all the contigs! It remains to be seen if it's faster, but it'll certainly be more convenient and use less disk space that having both!

A secondary goal is to refactor the contig retrieval stuff in the code base so that it uses the same API throughout. Once it does that, we can experiment with alternative storage mechanisms such as duckdb #339 quite easily!

Note that sqlite does not compress the contigs.

### CODE REVIEW

**Comment by domoritz** [comment]
Is this faster or why SQLite? If so, did you want to look into duckdb for even faster queries? What about some standard format like parquet?

**Comment by ctb** [comment]
also probably want to benchmark this 🤔

**Comment by ctb** [comment]
> Is this faster or why SQLite? If so, did you want to look into duckdb for even faster queries? What about some standard format like parquet?

(updated PR description with more details as to why, to answer this question!)

**Comment by domoritz** [comment]
Yeah, one file makes a lot of sense. 

Instead of duckdb, parquet (backed by arrow https://arrow.apache.org/docs/python/parquet.html) could be even better since it is compatible with many libraries and languages.

**Comment by ctb** [comment]
Whew. That was a lot of icky plumbing! I'll merge when tests pass.

**Comment by ctb** [comment]
Benchmark with v2.0b7, basically this PR --

full hu-s1 search --
```
    Command being timed: "python -m spacegraphcats.click run conf/hu-s1.json search"
    User time (seconds): 11436.74
    System time (seconds): 725.17
    Elapsed (wall clock) time (h:mm:ss or m:ss): 3:24:52
    Maximum resident set size (kbytes): 70 737 400
```

just sort:
```
    Command being timed: "python -m spacegraphcats.click run conf/hu-s1.json bcalm_catlas_sort"
    User time (seconds): 2053.59
    System time (seconds): 156.83
    Elapsed (wall clock) time (h:mm:ss or m:ss): 37:41.60
    Maximum resident set size (kbytes): 12 911 052
```

just bcalm_to_gxt:
```
    Command being timed: "python -m spacegraphcats.click run conf/hu-s1.json bcalm_catlas_prepare_input"
    User time (seconds): 627.18
    System time (seconds): 127.21
    Elapsed (wall clock) time (h:mm:ss or m:ss): 15:40.84
    Maximum resident set size (kbytes): 12 484 400
```

compare with https://github.com/spacegraphcats/spacegraphcats/pull/338#issuecomment-722519310 --

sort: 35m:33s, in 12.9 GB
output gxt: 18m:26s, in 14.9 GB

**Comment by ctb** [comment]
(so, some minor memory decrease in output gxt, and otherwise about the same time)

**Pull request merged**
