### PR TITLE
Fix two issues: failure of query_by_sequence on no match, and add catlas name to results

### LINKED ISSUE #252: Add catlas base name to results.csv
The `results.csv` file generated by a query does not currently contain the catlas name that the query was enacted upon. This information is only recorded in the folder name that the `results.csv` file is written in. Adding this information as a column in the `results.csv` would simplify comparing results across many samples (e.g., same query across many samples).

### PR DESCRIPTION
**Pull request by ctb**
Fixes #252 and #254.

@taylorreiter lmk if this looks good.

### CODE REVIEW

**Comment by taylorreiter** [comment]
Thanks @ctb! This fixes the error, but a new error comes up later given the empty file:

```
rule extract_contigs_single_file:
    input: 6006-04_k31_r1/contigs.fa.gz, 6006-04_k31_r1_search_oh0/VogtmannE_2016__MMR
S72980899ST-27-0-0__bin.41.fna.cdbg_ids.txt.gz
    output: 6006-04_k31_r1_search_oh0/VogtmannE_2016__MMRS72980899ST-27-0-0__bin.41.fn
a.cdbg_ids.contigs.fa.gz
    jobid: 251
    wildcards: queryname=VogtmannE_2016__MMRS72980899ST-27-0-0__bin.41.fna

/home/tereiter/github/ibd/.snakemake/conda/d24222af/bin/python -m spacegraphcats.searc
h.extract_contigs 6006-04_k31_r1 6006-04_k31_r1_search_oh0/VogtmannE_2016__MMRS7298089
9ST-27-0-0__bin.41.fna.cdbg_ids.txt.gz -o 6006-04_k31_r1_search_oh0/VogtmannE_2016__MM
RS72980899ST-27-0-0__bin.41.fna.cdbg_ids.contigs.fa.gz

Traceback (most recent call last):
  File "/home/tereiter/github/ibd/.snakemake/conda/d24222af/lib/python3.7/runpy.py", l
ine 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/tereiter/github/ibd/.snakemake/conda/d24222af/lib/python3.7/runpy.py", l
ine 85, in _run_code
    exec(code, run_globals)
  File "/home/tereiter/github/ibd/.snakemake/conda/d24222af/lib/python3.7/site-package
s/spacegraphcats/search/extract_contigs.py", line 67, in <module>
    sys.exit(main())
  File "/home/tereiter/github/ibd/.snakemake/conda/d24222af/lib/python3.7/site-packages/spacegraphcats/search/extract_contigs.py", line 46, in main
    offset_f = total_seqs / len(cdbg_shadow)
ZeroDivisionError: division by zero
extracting contigs to 6006-04_k31_r1_search_oh0/VogtmannE_2016__MMRS72980899ST-27-0-0__bin.41.fna.cdbg_ids.contigs.fa.gz.
```

**Comment by ctb** [comment]
yay cool

**Comment by ctb** [comment]
...how about now? :)

**Comment by taylorreiter** [comment]
This is working as expected now...thank you!

**Comment by ctb** [comment]
yay!

**Pull request merged**
