### PR TITLE
[MRG] Read extraction/examination code

### PR DESCRIPTION
**Pull request by ctb**
Adds functionality to go from shadow node IDs to assembled contigs (== linear node sequences in the cDBG) and the reads that were used to build the cDBG.  Lotsa code, lotsa changes, but much improved confidence in frontier search and read extraction, because we can now do a round-trip from reads->DBG->cDBG->catlas->search->reads.

Briefly,

* adds `search/extract_contigs_by_frontier.py` which lets us extract contigs by frontier search;
* adds `search/label_cdbg.py`, which indexes read data sets by cDBG contig;
* adds `search/extract_reads_by_frontier.py`, which provides a way to retrieve reads by frontier search (requires indexing with `search.label_cdbg` first);

Utility functions/code:

* copies block-gzipped sequence retrieval code over from BioPython into `search/bgzf/`; this is used for fast random access into read data files.

There are some new `make` targets for testing and demonstration:

* `dory-test` - do a quick run/check on all of the basic scripts
* `twofoo-extract` - run through everything on a real read data set

----

- [x] Does this PR change the contracted DBG, catlas, or minhash DB formats?
      If so, merge with care as this will require rebuilding some big files.

### CODE REVIEW

**Comment by sgsmob** [comment]
It appears the test cases have failed because you are calling `khmer.LinearAssembler()` with two arguments rather than one in `walk_dbg.py`.  Not really sure what that function does so I can't tell you what is going on.

**Comment by ctb** [comment]
@sgsmob yep, turns out that the correct version of khmer (branch `spacegraphcats`) is being overwritten by a version requirement in sourmash's setup.py. Sigh.

**Comment by ctb** [comment]
Ready for review and merge!

**Comment by ctb** [comment]
While there are a number of automated tests and checks that need to be added (#150, #149, #146) this has been the active branch for the last few months for me and I think it should be merged. Any objections? If not, please go ahead and merge (or I will in a few days).

**Comment by ctb** [comment]
I think #151 should be merged first, note.

**Comment by ctb** [comment]
Merging; this will automatically close #142, too.

**Pull request merged**
