### PR TITLE
Use marginal difference when greedily adding children. 

### PR DESCRIPTION
**Pull request by domoritz**

### CODE REVIEW

**Comment by domoritz** [comment]
https://github.com/spacegraphcats/spacegraphcats/pull/106/commits/11eecfb8f8e21acf88df3c1c6d67e2c6bd25fcbd is the relevant commit

**Comment by domoritz** [comment]
I don't understand why, but we are crashing with `Exception('Children cannot cover node.')`. I need some help from @ctb on this.

**Comment by bdsullivan** [comment]
This fixes #99.

**Comment by domoritz** [comment]
Duh, I think I know how to fix this. I'll try it when I have wifi.

**Pull request merged**
