### PR TITLE
add paired read indexing

### LINKED ISSUE #229: change reads output filename
After merge of #228, output reads are FASTQ if input reads are FASTQ. However, the filename specified by `conf/Snakefile` for `extract_reads.py` is still .fa.gz. For version 2, we should change this.

### LINKED ISSUE #284: Output forward and reverse reads as interleave pairs with extract_reads
Right now, `extract_reads` returns only the forward (or reverse) read in a pair of reads if only the forward (or reverse) read contains a kmer in the query nbhd. Is it possible to return both the forward and reverse read as interleaved pairs? I'm not sure this is desirable behavior, but it strikes me as being so for all biological purposes of nbhd queries. This would enable better use of sgc output by downstream tools (e.g. megahit, singlem, anything that performs better with paired-end reads) 

See https://github.com/wwood/singlem/issues/52 for an example of how to get around not having paired-end reads.

### PR DESCRIPTION
**Pull request by ctb**
This PR changes read extraction so that (by default) paired reads are output, when _either_ of the reads is found in the search. It does this by labeling paired reads with the same cDBG IDs in `index_reads`. (#284)

This PR also changes the default read output filename to be `reads.gz`, instead of `reads.fa.gz`. (#229)

Fixes https://github.com/spacegraphcats/spacegraphcats/issues/284
Fixes https://github.com/spacegraphcats/spacegraphcats/issues/229

- [x] allow expect_paired_reads to be set (on by default?), and barf if none are found in first ~100,000 reads or something
- [x] test extraction of reads #284
- [x] address output filename #229

### CODE REVIEW

**Comment by ctb** [comment]
some output!
```
% python -m spacegraphcats.click run twofoo-short twofoo-short_k31_r1/reads.bgz.labels2
loaded 108431 k-mers in index (0.0s)
walking read file: 'twofoo-short/twofoo-short.reads.bgz'
3.46e+05 bp in 2501 reads
975 paired of 2501 reads
found reads for 213 cDBG IDs
done; closing twofoo-short_k31_r1/reads.bgz.labels2!
[Thu Nov 12 12:36:21 2020]
Finished job 0.
1 of 1 steps (100%) done
Complete log: /Users/t/dev/spacegraphcats/.snakemake/log/2020-11-12T123620.462227.snakemake.log

-------- DONE --------

catlas output directory: twofoo-short_k31_r1
search output directory: twofoo-short_k31_r1_search_oh0
```

see esp **975 paired of 2501 reads**!!

**Comment by taylorreiter** [comment]
> see esp 975 paired of 2501 reads!!

Meaning the return is paired now? or what am I supposed to observe about that?

**Comment by ctb** [comment]
On Thu, Nov 12, 2020 at 12:54:30PM -0800, Taylor Reiter wrote:
> > see esp 975 paired of 2501 reads!!
> 
> Meaning the return is paired now? or what am I supposed to observe about that?

it's being detected (well, and _should_ be returned, tho I haven't checked).

buzzkill :0

**Comment by ctb** [comment]
things to test --

- [x] paired reads are labeled properly
- [x] paired reads are extracted in the right order (offset order in reads file)
- [x] /1 and /2 work, as well as SRR-identical-names-style
- [x] add option to require that some paired reads be present

**Comment by ctb** [comment]
@taylorreiter this functionality works AFAICT, so I'm going to merge when tests pass. Happy to adjust UX based on feedback by you later ;)

**Comment by taylorreiter** [comment]
Yay! I'll post UX in the issues after I try it if I have any, excited to see how it helps downstream interpretation!

**Comment by ctb** [comment]
👍 

I was thinking of doing a hu-s1 rerun with it turned on, as one way to evaluate.

**Comment by taylorreiter** [comment]
that would be great!

**Comment by ctb** [comment]
On Fri, Nov 13, 2020 at 08:51:54AM -0800, Taylor Reiter wrote:
> that would be great! 

automation FTW :)

**Pull request merged**
