### PR TITLE
[MRG] add thread/cores parameter to bcalm in the Snakefile

### LINKED ISSUE #217: adjust bcalm execution in conf/Snakefile to use threads
Right now, bcalm is not told to use multiple threads. (It may choose to do so anyway, based on slurm etc environment variables, but it'd be nice to control it explicitly!)

The trick is, we don't want to use the internal snakemake thread parameter, because spacegraphcats is memory limited on large datasets and we don't want snakemake trying to run multiple spacegraphcats commands at once. So instead we probably want to provide a bcalm-specific parameter in the config file.

### PR DESCRIPTION
**Pull request by ctb**
Fixes https://github.com/spacegraphcats/spacegraphcats/issues/217.

Also adds a badge for the latest PyPI release to the README.

### CODE REVIEW

**Comment by ctb** [comment]
Ready for review & merge, @taylorreiter !

**Review by taylorreiter — COMMENTED** [review]
should this be added to the conf file? will snakemake auto scale down if it's run with 1 thread instead of 16?

When i run sgc in a snakefile, I usually just run it all the way through to read extraction in one rule...and with ~32gb ram with 1 thread. This would massively change the # of jobs that could be run at once but hard coding this.

**Comment by ctb** [comment]
snakemake should auto-scale down to one thread if `-j 1` is specified.

**Comment by ctb** [comment]
basically, I'm not 100% sure of the memory implications, but 
* this PR makes snakemake communicate with bcalm about threads, which seems like a good start!
* it's not clear to me how bcalm memory usage increases with multiple threads, but bcalm is also not the main memory hog in spacegraphcats.

**Review by taylorreiter — APPROVED** [review]
cool sounds great, i will report if it explodes etc :)

**Pull request merged**
