### PR TITLE
ci: add flake to tests, format with black, and add precommit hooks

### PR DESCRIPTION
**Pull request by domoritz**
This will cause a bit more work one time (need to run black on prs as well) but then should reduce friction for prs or maintaining style in the future. 

* Adds flake and black to ci
* Adds flake and black to precommit hooks
* Adds flake8 config file
* Also tests scripts for flake issues

I was following https://ljvmiranda921.github.io/notebook/2018/06/21/precommits-using-black-and-flake8/

### CODE REVIEW

**Comment by ctb** [comment]
thanks - I want to dig into this a bit and try it out before committing (heh)! if you separate the fixes from the precommit hooks I'll happily merge those tho!

**Comment by domoritz** [comment]
Sure. You want me to just remove precommit hooks but leave everything else?

**Comment by ctb** [comment]
actually, @luizirber is telling me to just go ahead with it 👍 

let's give it a try!

**Comment by domoritz** [comment]
🎉

**Comment by domoritz** [comment]
I'll let you press the merge button @ctb

**Comment by luizirber** [comment]
(I have a similar PR in sourmash: https://github.com/dib-lab/sourmash/pull/696
I based it on the setup that [tox](https://github.com/tox-dev/tox) uses)

**Pull request merged**
